global:
 scrape_interval: 10s
 evaluation_interval: 10s
scrape_configs:
 - job_name: 'kafka'
   static_configs:
    - targets:
      - kafka:7071   # Kafka 1 - change IP for your use case
#  - job_name: 'zookeeper'
#    static_configs:
#     - targets:
#       - .....:8080
